# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FYUntil' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FYUntil

 pod 'ReactiveCocoa','~>2.0'
 pod 'Masonry','~>1.0.2'
 pod 'SDWebImage', '~>3.8.2'

end
